welcome:
  first_time_issue: "👋 Howdy, **{{author}}** — thanks for opening your first issue!"
  returning_issue: "🔁 Welcome back, **{{author}}**! Thanks for your continued contributions."
  first_time_pr: "🎉 Your first pull request is appreciated, **{{author}}** — thank you!"
  returning_pr: "🤠 You're awesome, **{{author}}**! Thanks for another PR."

labels:
  issues:
    - needs-triage
  prs:
    - awaiting-review

autoCloseOnTitleContains: "complete" # Auto-close issues or PRs if "complete" appears in the title

autoAssignAuthor: true               # Auto-assign the issue/PR author
autoUnassignIfRemoved: true         # Auto-unassign users removed from reviewers or assignees
syncAssigneesWithReviewers: true    # Sync PR assignees with reviewers
